version: '3.7'

services:
  app-service:
    image: erikx3/frogy-agrobioapp:ts-22.01.18.1
    ports:
      - "4200:80"
    networks:
      - frontend
  flask:
    build: ./src
    container_name: flask
    restart: always
    environment:
      - APP_NAME=AgroBioApi
      - APP_ENV=prod"
      - APP_DEBUG=False
    expose:
      - 4000
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    environment:
      - APP_ENV=prod
      - APP_NAME=webserver
      - APP_DEBUG=true
      - SERVICE_NAME=webserver
    ports:
      - "4000:4000"
    networks:
    - frontend

  mongodb:
    image: mongo
    restart: always
    command: mongod --noauth
    volumes:
      - ./mongodbdata:/data/db
    ports:
      - 27018:27017
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge